### ISSUE TITLE
能不能考慮提供源文件？

### ISSUE THREAD

**Issue by Marcus98T** [GuiWonder/EarlySummerMincho#1]
我想你用 FontForge 來編輯本字體，那麼你能提供 sfd 源文件嗎？謝謝。

**Comment by GuiWonder** [comment]
我是使用 FontCreator 修改的可變 ttf ，使用的源文件格式是 fcp，[這裏是分享鏈接](https://www.wenshushu.cn/f/bpsbk0c3lhf)，希望能幫到你。

**Comment by GuiWonder** [comment]
本字體的製作過程是使用思源宋體可變 ttf ，首先修改 cmap 映射 (`./codes/step01.py`) 得到新的可變 ttf，然後使用 FontCreator 修改這個可變 ttf ，最後使用修改後的可變 ttf 生成靜態字體 (`./codes/step02.py`) 。全過程都是修改 ttf ，沒有用到開源格式。如果我把 ttf 轉成 UFO 當作「源文件」提供給你，我覺得好像沒什麼意義，而且感覺還有點欺騙你的意思。倒不如你直接修改可變 ttf 或者通過工具來得到其的他格式來編輯字體。
