### ISSUE TITLE
我對字體優化的建議

### ISSUE THREAD

**Issue by Steve-Yuu** [GuiWonder/EarlySummerMincho#2]
1、部分生僻字可借用思源1的字圖，基本庫和擴展A及其他，比如說愻等等（涉及的字較多，難以一下子列舉，思源1jp版基本庫的字很多是仿照JMJ，也就是說IPAmj的基本區的字形，，不過字形也不能保證百分百完美）
<img width="76" alt="image" src="https://github.com/GuiWonder/EarlySummerMincho/assets/108906358/937b8744-a2d0-4d82-9e0a-e564e96d34a6">

<img width="74" alt="image" src="https://github.com/GuiWonder/EarlySummerMincho/assets/108906358/997fb9c8-db84-4001-ba82-6ef017700fd4">
2、悤部件不統一，可以考慮都做成“囪”，心字底建議保留思源Jp寫法而不是直接粘貼TW的，可以借用思源1字形重繪
<img width="619" alt="image" src="https://github.com/GuiWonder/EarlySummerMincho/assets/108906358/388ce3ee-94cf-4aaf-ae0e-2d7096e80376">
另外，u+7e0f需要優化，圖二是思源1，不知道思源2是否刪除了其舊字形字圖，或者説是思源2本身的問題
<img width="35" alt="image" src="https://github.com/GuiWonder/EarlySummerMincho/assets/108906358/c5ea941e-02e9-42f4-903e-0f18fc53f8b5">
<img width="35" alt="image" src="https://github.com/GuiWonder/EarlySummerMincho/assets/108906358/e689b48e-1bec-4c56-bae8-afc3d13c4461">

這只是部分缺點，總體來說這個字體的確很不錯

**Comment by GuiWonder** [comment]
感謝建議！本字體基於思源宋體可變ttf版本製作。由於思源1僅提供了靜態otf，未提供可變版本，所以思源1無法應用到本字體上。對字圖的優化還需要通過手動逐字調整。

**Comment by Steve-Yuu** [comment]
> 感謝建議！本字體基於思源宋體可變ttf版本製作。由於思源1僅提供了靜態otf，未提供可變版本，所以思源1無法應用到本字體上。對字圖的優化還需要通過手動逐字調整。

的確如此，不過對於某些字可以再優化一下，或者考慮基於思源1做不可變多字重版本（不知是否可以接受，若不行也不強求）

**Comment by GuiWonder** [comment]
新版已對上述部件做了一些調整。
