### ISSUE TITLE
“纟”

### ISSUE THREAD

**Issue by garfieldLSY** [GuiWonder/EarlySummerMincho#3]
可以參考一下I.明體。

**Comment by GuiWonder** [comment]
本字體的部件基本都是思源宋體已有的部件。簡體「纟」部件來源於「糹」的草寫，由於筆畫缺失嚴重，強行標準化為「舊字形」很難做到協調美觀。對於我本人來說難度太大。
查詢了一些關於簡體字舊印刷體的資料，無論是簡體的還是「半簡體」的，「纟」部件幾乎和現代印刷體無異（如圖）。I.明體的「纟」部件在舊印刷體中非常少見（也可能沒有）。本字體不像I.明體那樣追求字源，「纟」部件還是保持原樣更合適一些。  

![pic01](https://github.com/GuiWonder/EarlySummerMincho/assets/55447192/3d5d55e9-5321-426d-9620-96959c29a19f)  
![pic02](https://github.com/GuiWonder/EarlySummerMincho/assets/55447192/c37e00bd-6193-4f0a-9968-11a249f182f4)  
![pic03](https://github.com/GuiWonder/EarlySummerMincho/assets/55447192/c1171ef1-67d7-4abb-b60e-4ebf92542516)

**Comment by garfieldLSY** [comment]
👌🏻，感謝您的答復。
