### ISSUE TITLE
可不可以考虑推出适合阅读的屏显字体？

### ISSUE THREAD

**Issue by ChellyL** [GuiWonder/EarlySummerMincho#4]
如题，大佬做的字体都挺好的，看效果图很适合阅读，但我发现拿到kindle或者手机上阅读还是会觉得笔画稍细，
可否参考方正悠宋、方正屏显雅宋或者屏显臻宋、極影毀片文宋等字体推出笔画稍微加粗的屏显字体？

**Comment by GuiWonder** [comment]
谢谢反馈！由于我对屏显字体不太熟悉，屏显字体制作可能需要一些时间。

**Comment by ChellyL** [comment]
好的，感谢回复：）

**Comment by GuiWonder** [comment]
新版已添加笔画加粗的版本“屏阅初夏明朝体(EarlySummerMincho-Screen)”，感谢您的建议。

**Comment by ChellyL** [comment]
感谢制作，效果很好：）
![screenshot_2023_08_07T12_04_04+0800](https://github.com/GuiWonder/EarlySummerMincho/assets/38887991/5fc41da6-afae-4bfb-b795-c2cd995aee8f)
